# Generated by Django 2.0.4 on 2019-08-03 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('type', models.CharField(choices=[('ES', 'Estudiante'), ('TE', 'Docente')], max_length=2, verbose_name='Tipo de usuario')),
                ('first_name', models.CharField(max_length=25, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=25, verbose_name='Apellidos')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.IntegerField(verbose_name='Código')),
            ],
            options={
                'verbose_name_plural': 'Programas Académicos',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cc', models.CharField(max_length=25, unique=True, verbose_name='Cédula de ciudadania')),
                ('first_name', models.CharField(max_length=25, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial')),
                ('uptc_serial', models.CharField(blank=True, max_length=25, null=True, verbose_name='UPTC-Serial')),
                ('state', models.CharField(choices=[('IN', 'En servicio'), ('OU', 'Fuera de servicio'), ('FR', 'Fragil')], max_length=2, verbose_name='Estado')),
                ('status', models.CharField(choices=[('AV', 'Disponible'), ('OL', 'En Prestamo'), ('IM', 'En Mantenimiento'), ('NA', 'No Disponible')], max_length=2, verbose_name='Disponibilidad')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='ComponentStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('level', models.CharField(choices=[('L1', 'Nivel 1'), ('L2', 'Nivel 2'), ('L3', 'Nivel 3'), ('L4', 'Nivel 4')], max_length=2, verbose_name='Nivel')),
                ('image', models.ImageField(upload_to='static/images')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Stock de componentes',
            },
        ),
        migrations.CreateModel(
            name='ComputerEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('brand', models.CharField(max_length=25, verbose_name='Marca')),
                ('model_computer', models.CharField(max_length=25, verbose_name='Modelo')),
                ('room_id', models.IntegerField(verbose_name='ID')),
                ('ram_memory', models.IntegerField(blank=True, null=True, verbose_name='Memoria RAM (GB)')),
                ('hdd', models.IntegerField(blank=True, null=True, verbose_name='Memoria HDD (GB)')),
                ('ssd', models.IntegerField(blank=True, null=True, verbose_name='Memoria SSD (GB)')),
                ('charger', models.BooleanField(verbose_name='Cargador')),
                ('battery', models.BooleanField(verbose_name='Batería')),
                ('optical_unit', models.BooleanField(verbose_name='Unidad Óptica')),
                ('briefcase', models.BooleanField(verbose_name='Maletín')),
            ],
            options={
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('date_start', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Fecha final')),
                ('state_loan', models.SmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Finalizado')])),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Academic', verbose_name='Usuario')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Administrator', verbose_name='Administrador')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='LoanComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('state', models.SmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Entregado')])),
                ('date_end', models.DateField(verbose_name='Fecha de entrega')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='telematics.Component', verbose_name='Componente')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Loan', verbose_name='Prestamo')),
            ],
            options={
                'verbose_name_plural': 'Prestamos Componentes',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('date_start', models.DateField(verbose_name='Fecha de inicio')),
                ('date_end', models.DateField(blank=True, verbose_name='Fecha de finalización')),
                ('maintenance_type', models.SmallIntegerField(choices=[(0, 'preventive'), (1, 'corrective')], verbose_name='Tipo de mantenimiento')),
                ('state', models.SmallIntegerField(choices=[(0, 'in maintenance'), (1, 'finalized')], verbose_name='Estado')),
                ('maintenance', models.TextField(verbose_name='Mantenimiento')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recomendaciones')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Administrator', verbose_name='Administrador')),
            ],
            options={
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Component', verbose_name='Componente')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Maintenance', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name_plural': 'Mantenimientos Componentes',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('type_place', models.CharField(choices=[('CI', 'Ciudad'), ('SE', 'Sede'), ('BO', 'Bodega')], max_length=2, verbose_name='Tipo lugar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='telematics.Places')),
            ],
            options={
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('type', models.SmallIntegerField(choices=[(0, 'Exedió tiempo de préstamos'), (1, 'Daño'), (2, 'Pérdida')])),
                ('state', models.SmallIntegerField(choices=[(0, 'sanctioned'), (1, 'finalized')], verbose_name='Tipo de sanción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('loan_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.LoanComponent', verbose_name='Prestamo')),
            ],
            options={
                'verbose_name_plural': 'Sanciones',
            },
        ),
        migrations.CreateModel(
            name='TypeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Tipos de componentes',
            },
        ),
        migrations.AddField(
            model_name='componentstock',
            name='type_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.TypeComponent', verbose_name='Tipo de Componente'),
        ),
        migrations.AddField(
            model_name='component',
            name='computer_equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telematics.ComputerEquipment', verbose_name='Equipo de cómputo'),
        ),
        migrations.AddField(
            model_name='component',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Places', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='component',
            name='stock_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.ComponentStock', verbose_name='Componente'),
        ),
    ]
