# Generated by Django 2.0.4 on 2019-04-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ES', 'Estudiante'), ('TE', 'Docente')], default='ES', max_length=2, verbose_name='Tipo de usuario')),
                ('code', models.CharField(max_length=25, verbose_name='Código')),
                ('first_name', models.CharField(max_length=25, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=25, verbose_name='Apellidos')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.IntegerField(verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=25, verbose_name='Cédula de ciudadania')),
                ('first_name', models.CharField(max_length=25, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=25, null=True, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial')),
                ('uptc_serial', models.CharField(blank=True, max_length=25, null=True, verbose_name='UPTC-Serial')),
                ('state', models.CharField(choices=[('IN', 'En servicio'), ('OU', 'Fuera de servicio'), ('FR', 'Fragil')], default='IN', max_length=2, verbose_name='Estado')),
                ('status', models.CharField(choices=[('AV', 'Disponible'), ('OL', 'En Prestamo'), ('IM', 'En Mantenimiento'), ('NA', 'No Disponible')], default='AV', max_length=2, verbose_name='Disponibilidad')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
                ('observations', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones')),
                ('level', models.CharField(choices=[('L1', 'Nivel 1'), ('L2', 'Nivel 2'), ('L3', 'Nivel 3'), ('L4', 'Nivel 4')], default='L2', max_length=2, verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25, verbose_name='Marca')),
                ('model', models.CharField(max_length=25, verbose_name='Modelo')),
                ('room_id', models.IntegerField(verbose_name='ID')),
                ('ram_memory', models.IntegerField(blank=True, null=True, verbose_name='Memoria RAM (GB)')),
                ('hdd', models.IntegerField(blank=True, null=True, verbose_name='Memoria HDD (GB)')),
                ('ssd', models.IntegerField(blank=True, null=True, verbose_name='Memoria SSD (GB)')),
                ('charger', models.BooleanField(verbose_name='Cargador')),
                ('battery', models.BooleanField(verbose_name='Batería')),
                ('optical_unit', models.BooleanField(verbose_name='Unidad Óptica')),
                ('briefcase', models.BooleanField(verbose_name='Maletín')),
            ],
        ),
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sede')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Fecha de inicio')),
                ('date_end', models.DateField(blank=True, verbose_name='Fecha de finalización')),
                ('state', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'finalized')], default=0)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Academic', verbose_name='Usuario')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Administrator', verbose_name='Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='LoanComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Component', verbose_name='Componente')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Loan', verbose_name='Prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Fecha de inicio')),
                ('date_end', models.DateField(blank=True, verbose_name='Fecha de finalización')),
                ('maintenance_type', models.SmallIntegerField(choices=[(0, 'preventive'), (1, 'corrective')], default=1, verbose_name='Tipo de mantenimiento')),
                ('state', models.SmallIntegerField(choices=[(0, 'in maintenance'), (1, 'finalized')], default=0, verbose_name='Estado')),
                ('maintenance', models.CharField(max_length=50, verbose_name='Mantenimiento')),
                ('recommendations', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recomendaciones')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Administrator', verbose_name='Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Component', verbose_name='Componente')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Maintenance', verbose_name='Mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(0, 'sanctioned'), (1, 'finalized')], default=0, verbose_name='Tipo de sanción')),
                ('observation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observación')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Loan', verbose_name='Prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='TypeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('headquarters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Headquarters', verbose_name='Sede')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='computer_equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telematics.ComputerEquipment', verbose_name='Equipo de cómputo'),
        ),
        migrations.AddField(
            model_name='component',
            name='type_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.TypeComponent', verbose_name='Tipo de Componente'),
        ),
        migrations.AddField(
            model_name='component',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Warehouse', verbose_name='Almacén'),
        ),
    ]
