# Generated by Django 2.0.4 on 2019-03-08 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telematics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academic',
            name='type',
            field=models.CharField(default='NA', max_length=2, verbose_name='Tipo de usuario'),
        ),
    ]
