# Generated by Django 2.0.4 on 2019-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
    ]
