# Generated by Django 2.0.4 on 2019-04-10 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telematics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='headquarters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.Headquarters'),
        ),
        migrations.AddField(
            model_name='academic',
            name='academic_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telematics.AcademicProgram', verbose_name='Programa Académico'),
        ),
        migrations.AddField(
            model_name='academic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='loancomponent',
            unique_together={('loan', 'component')},
        ),
    ]
