# Generated by Django 2.0.4 on 2019-04-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematics', '0002_auto_20190410_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='cc',
            field=models.CharField(max_length=25, unique=True, verbose_name='Cédula de ciudadania'),
        ),
    ]
