# Generated by Django 2.0.4 on 2019-08-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematics', '0002_auto_20190618_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstock',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
