# Generated by Django 2.0.4 on 2019-04-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telematics', '0003_auto_20190410_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicprogram',
            options={'verbose_name': 'Programa Académico'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Componente'},
        ),
        migrations.AlterModelOptions(
            name='computerequipment',
            options={'verbose_name': 'Computadore'},
        ),
        migrations.AlterModelOptions(
            name='headquarters',
            options={'verbose_name': 'Sede'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Prestamo'},
        ),
        migrations.AlterModelOptions(
            name='loancomponent',
            options={'verbose_name': 'Prestamo Componente'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='maintenancecomponent',
            options={'verbose_name': 'Mantenimiento Componente'},
        ),
        migrations.AlterModelOptions(
            name='sanction',
            options={'verbose_name': 'Sancione'},
        ),
        migrations.AlterModelOptions(
            name='typecomponent',
            options={'verbose_name': 'Tipos de componente'},
        ),
    ]
