# Generated by Django 2.0.4 on 2019-04-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telematics', '0004_auto_20190410_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Bodega'},
        ),
    ]
