# Generated by Django 2.0.4 on 2019-04-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematics', '0005_auto_20190410_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicprogram',
            options={'verbose_name_plural': 'Programas Académicos'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name_plural': 'Componentes'},
        ),
        migrations.AlterModelOptions(
            name='computerequipment',
            options={'verbose_name_plural': 'Computadores'},
        ),
        migrations.AlterModelOptions(
            name='headquarters',
            options={'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name_plural': 'Prestamos'},
        ),
        migrations.AlterModelOptions(
            name='loancomponent',
            options={'verbose_name_plural': 'Prestamos Componentes'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AlterModelOptions(
            name='maintenancecomponent',
            options={'verbose_name_plural': 'Mantenimientos Componentes'},
        ),
        migrations.AlterModelOptions(
            name='sanction',
            options={'verbose_name_plural': 'Sanciones'},
        ),
        migrations.AlterModelOptions(
            name='typecomponent',
            options={'verbose_name_plural': 'Tipos de componentes'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'Bodegas'},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
