# Generated by Django 2.0.4 on 2019-04-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telematics', '0006_auto_20190410_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerequipment',
            old_name='model',
            new_name='model_computer',
        ),
    ]
